// GENERATED by frontend/scripts/gen-docs-index.mjs from docs/guide/usage.md.
// Do not edit by hand; edit the Reading Order in usage.md and re-run:
//   node frontend/scripts/gen-docs-index.mjs

export interface DocEntry {
  slug: string;
  title: string;
  section: string;
  desc: string;
}

export const docIndex: DocEntry[] = [
  { slug: 'usage', title: "Usage Guide", section: "Get Started", desc: "Reading order and common workflows." },
  { slug: 'getting-started', title: "Getting Started", section: "Get Started", desc: "Installation, credentials, sign-in, first task end to end." },
  { slug: 'concepts', title: "Concepts", section: "Get Started", desc: "The mental model: workspaces, tasks, specs, agents, and the autonomy spectrum." },
  { slug: 'board', title: "Board", section: "Use Wallfacer", desc: "The task board: lifecycle, dependencies, batch creation, search, the task detail view." },
  { slug: 'chat', title: "Chat", section: "Use Wallfacer", desc: "The dedicated chat surface: sessions, slash commands, @mentions." },
  { slug: 'plan', title: "Plan", section: "Use Wallfacer", desc: "Spec mode: the spec tree, lifecycle states, dispatch, and planning conversations." },
  { slug: 'agent-graph', title: "Agent Graph", section: "Use Wallfacer", desc: "Defining agents, composing fleets, harness pinning, live traces." },
  { slug: 'routines', title: "Routines", section: "Use Wallfacer", desc: "Scheduled cards that spawn fresh tasks on an interval." },
  { slug: 'whiteboard', title: "Whiteboard", section: "Use Wallfacer", desc: "The free-form drawing canvas." },
  { slug: 'automation', title: "Automation", section: "Operate", desc: "Autoimplement, auto-test, auto-submit, auto-retry, circuit breakers." },
  { slug: 'oversight', title: "Oversight", section: "Operate", desc: "Oversight summaries, timelines, logs, diff review, cost and usage analytics." },
  { slug: 'mission-control', title: "Mission Control", section: "Operate", desc: "The unified spec and task graph, acting on the pipeline." },
  { slug: 'workspaces', title: "Workspaces", section: "Operate", desc: "Workspace management, git integration, branches, GitHub." },
  { slug: 'configuration', title: "Configuration", section: "Operate", desc: "Settings, environment variables, harness selection, CLI reference, keyboard shortcuts." },
];
